name: Sources  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /sources get lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-g.zip sources/get/index.js node_modules
      - name: source get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-g
            zip_file: m-s-sources-g.zip
      - name: /sources post lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-po.zip sources/post/index.js node_modules
      - name: source get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-po
            zip_file: m-s-sources-po.zip
      - name: /sources/{source_id} get lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-source-g.zip sources/source_id/get/index.js node_modules
      - name: source get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-source-g
            zip_file: m-s-sources-source-g.zip
      - name: /sources/{source_id} put lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-source-pu.zip sources/source_id/put/index.js node_modules
      - name: source get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-source-pu
            zip_file: m-s-sources-source-pu.zip
      - name: /sources/{source_id} delete lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-source-d.zip sources/source_id/delete/index.js node_modules
      - name: source get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-source-d
            zip_file: m-s-sources-source-d.zip          
      - name: /sources/{source_id}/tags get lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-source-tags-g.zip sources/source_id/tags/get/index.js node_modules
      - name: sources get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-source-tags-g
            zip_file: m-s-sources-source-tags-g.zip
      - name: /sources/{source_id}/tags post lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sources-source-tags-po.zip sources/source_id/tags/post/index.js node_modules
      - name: sources get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sources-source-tags-po
            zip_file: m-s-sources-source-tags-po.zip
      - name: /sources/bookmarklet get lambda deploy zip
        uses: algorotoscope/sources@main
        with:
            args: zip -qq -r m-s-sourcesbookmarklet-g.zip sources/bookmarklet/get/index.js node_modules
      - name: sources get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-east-1
            function_name: m-s-sourcesbookmarklet-g
            zip_file: m-s-sourcesbookmarklet-g.zip  
                      